---
value:
  id: 101
  title: "[A-1234] Error found in core/models.py file'"
  body: |-
    You have used an email that already exists for the user_email_uniq field.
     ## DETAILS:

    The (email)=(Octocat@github.com) already exists.

     The error was found in core/models.py in get_or_create_user at line 62.

     self.save()
