---
# Example of a dismissed Dependabot alert
value:
  number: 2
  state: dismissed
  dependency:
    package:
      ecosystem: pip
      name: django
    manifest_path: path/to/requirements.txt
    scope: runtime
  security_advisory:
    ghsa_id: GHSA-rf4j-j272-fj86
    cve_id: CVE-2018-6188
    summary: >-
      Django allows remote attackers to obtain potentially
      sensitive information by leveraging data exposure from
      the confirm_login_allowed() method, as demonstrated by
      discovering whether a user account is inactive
    description: >-
      django.contrib.auth.forms.AuthenticationForm in Django 2.0 before 2.0.2,
      and 1.11.8 and 1.11.9, allows remote attackers to obtain potentially sensitive
      information by leveraging data exposure from the confirm_login_allowed() method,
      as demonstrated by discovering whether a user account is inactive.
    vulnerabilities:
      - package:
          ecosystem: pip
          name: django
        severity: high
        vulnerable_version_range: ">= 2.0.0, < 2.0.2"
        first_patched_version:
          identifier: "2.0.2"
      - package:
          ecosystem: pip
          name: django
        severity: high
        vulnerable_version_range: ">= 1.11.8, < 1.11.10"
        first_patched_version:
          identifier: "1.11.10"
    severity: high
    cvss:
      vector_string: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
      score: 7.5
    cwes:
      - cwe_id: CWE-200
        name: Exposure of Sensitive Information to an Unauthorized Actor
    identifiers:
      - type: GHSA
        value: GHSA-rf4j-j272-fj86
      - type: CVE
        value: CVE-2018-6188
    references:
      - url: https://nvd.nist.gov/vuln/detail/CVE-2018-6188
      - url: https://github.com/advisories/GHSA-rf4j-j272-fj86
      - url: https://usn.ubuntu.com/3559-1/
      - url: https://www.djangoproject.com/weblog/2018/feb/01/security-releases/
      - url: http://www.securitytracker.com/id/1040422
    published_at: "2018-10-03T21:13:54Z"
    updated_at: "2022-04-26T18:35:37Z"
    withdrawn_at: null
  security_vulnerability:
    package:
      ecosystem: pip
      name: django
    severity: high
    vulnerable_version_range: ">= 2.0.0, < 2.0.2"
    first_patched_version:
      identifier: "2.0.2"
  url: https://api.github.com/repos/octocat/hello-world/dependabot/alerts/2
  html_url: https://github.com/octocat/hello-world/security/dependabot/2
  created_at: "2022-06-15T07:43:03Z"
  updated_at: "2022-08-23T14:29:47Z"
  dismissed_at: "2022-08-23T14:29:47Z"
  dismissed_by:
    login: octocat
    id: 1
    node_id: MDQ6VXNlcjE=
    avatar_url: https://github.com/images/error/octocat_happy.gif
    gravatar_id: ""
    url: https://api.github.com/users/octocat
    html_url: https://github.com/octocat
    followers_url: https://api.github.com/users/octocat/followers
    following_url: https://api.github.com/users/octocat/following{/other_user}
    gists_url: https://api.github.com/users/octocat/gists{/gist_id}
    starred_url: https://api.github.com/users/octocat/starred{/owner}{/repo}
    subscriptions_url: https://api.github.com/users/octocat/subscriptions
    organizations_url: https://api.github.com/users/octocat/orgs
    repos_url: https://api.github.com/users/octocat/repos
    events_url: https://api.github.com/users/octocat/events{/privacy}
    received_events_url: https://api.github.com/users/octocat/received_events
    type: User
    site_admin: false
  dismissed_reason: tolerable_risk
  dismissed_comment: This alert is accurate but we use a sanitizer.
  fixed_at: null
